server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Powered-By "PHP/8.2.12" always;
    add_header X-Pingback "/xmlrpc.php" always;

    location = /wp-json/ {
        default_type application/json;
        return 200 '{"name":"Vulkan Vegas Polska","description":"Niezale\u017cny portal afiliacyjny","url":"https:\/\/vulkan-vegas-kasyno.com.pl","home":"https:\/\/vulkan-vegas-kasyno.com.pl","gmt_offset":1,"timezone_string":"Europe\/Warsaw","namespaces":["wp\/v2","oembed\/1.0"],"authentication":{},"routes":{}}';
    }

    location / {
        try_files $uri $uri/ $uri/index.html =404;
    }

    error_page 404 /404.html;
}
